### GET REQUEST
POST http://localhost:5000/elearning-module-a887d/us-central1/app/auth/create-token

### POST REQUEST
POST http://localhost:4000/auth/createTokenModel

{"CName":"INTRODUCTION","LNo": 2143,"LName":"Lesson 400","LNotes":"Interesting Description","LVideo":"https://example3.com"} 

### AUTHORIZATION REQUEST 
GET http://localhost:5000/elearning-module-a887d/us-central1/app/oAuth/authorizationUri
### FETCH ACCESS TOKEN
# GET http://localhost:5000/elearning-module-a887d/us-central1/app/oAuth/getToken?code=4/0AZEOvhVHvn7_-tKFyfs1td7rGXLIZYsFMxvFYVIqAZ7ptKPB-BtnClD7XMGbxNVNTqlTEg
GET http://localhost:4000/oAuth/getToken?code=4/0AZEOvhVHvn7_-tKFyfs1td7rGXLIZYsFMxvFYVIqAZ7ptKPB-BtnClD7XMGbxNVNTqlTEg
### NEW FETCH
GET http://localhost:5000/elearning-module-a887d/us-central1/app/oAuth/getToken?code=4%2F0AZEOvhUb-4BqNManKZZy__qXJHynCkI8JEyVPfkTTfUBLsQBRSutrZ024arW5ciw9fvXaA&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload

### RESOURCE DELETE REQUEST
POST http://localhost:4000/auth/create-token

### MAKING PAYMENT TO TINYPESA
POST https://bulksms-asenawritescode.koyeb.app/api/v1/account/pay
content-type: application/json
apikey:9d1d8bb393c14550a5dfae8a2a1d5bd3

{"phone":"0112615416","amount":20}
###
POST https://bulksms-asenawritescode.koyeb.app/api/v1/account/balance
content-type: application/json
apikey:9d1d8bb393c14550a5dfae8a2a1d5bd3

{"phone":"0112615416"}

### SENDING AN SMS WITH TINYPESA
POST https://bulksms-asenawritescode.koyeb.app/api/v1/sms/send
content-type: application/json
apikey:9d1d8bb393c14550a5dfae8a2a1d5bd3

{"phone":"0112615416","message":"Testing endpoint ","recipient":["0112615416"]}


### DEBUG EMAIL

POST http://localhost:4000/auth/email
content-type: application/json

{
    "contacts": ["alfredgithinji87@gmail.com"],
    "subject":"READY FOR USE",
    "text":"Hello there , text version can be externalized!"
}

### FETCH AGGREGATED USERS
GET http://localhost:4000/auth/aggregated-users

### FETCH AGGREGATED COURSES
GET http://localhost:4000/course/aggregated

### FETCH AGGREGATED UNITS 
GET http://localhost:4000/unit/aggregated

### FETCH AGGREGATED CHAPTERS
GET http://localhost:4000/chapter/aggregated


### FETCH ALL MESSAGES
GET http://localhost:4000/message/all-messages

### FETCH ALL EMAILS
GET http://localhost:4000/email/all-emails


### FETCH AGGREGATED LESSONS
GET http://localhost:4000/lesson/aggregated64fadac357cd2f1690869b42

### SENDING MESSAGES VIA WHATSAPP
GET https://web.whatsapp.com/send?phone="+254112615416"&text="Hello there "&app_absent=0
### FETCH  LESSON
GET http://localhost:4000/lesson/64fadfd35f429afdbf72b4c8

### DELETE COURSES TRIAL
DELETE  http://localhost:4000/course/64fbf326b1ccf748e07eab38